### ISSUE TITLE
rss feed for posts?

### ISSUE THREAD

**Issue by phanirithvij** [fzakaria/fzakaria.com#14]
Just a suggestion, many blogs usually have rss feeds and they are very convinient to be notified of new posts.

**Comment by fzakaria** [comment]
Hi!

I think I'm using jekyll-feed that publishes Atom.
Here is the atom feed you can subscribe too: https://fzakaria.com/feed.xml

Taken from my HTML `<head>`
```xml
<link type="application/atom+xml" rel="alternate" href="https://fzakaria.com/feed.xml" title="Farid Zakaria's Blog">
```

**Comment by phanirithvij** [comment]
Can you add an RSS icon somewhere in the footer or in the Archive page?

**Comment by fzakaria** [comment]
I'l look into it; thanks for the suggestion.

Since it's a tag in HEAD though any RSS/ATOM feed reader plugin should recognize the site as well.

**Comment by alurm** [comment]
I agree, it'd be nice to have a link to the feed somewhere on the site. I had to go into HTML to see feed's address, since I don't use any special extensions for feeds in my browser.

**Comment by fzakaria** [comment]
Added icon.
