### ISSUE TITLE
tailscale is magic post

### ISSUE THREAD

**Issue by happysalada** [fzakaria/fzakaria.com#3]
Hi!

   Thanks for the [great post](https://github.com/fzakaria/fzakaria.com/edit/master/_posts/2020-09-17-tailscale-is-magic-even-more-so-with-nixos.md) about tailscale and NixOS.
   
   One question I have, how did you know which UDP port to open ? I haven't seen that information anywhere.

   Also, completely unrelated, but I hope you haven't given up on the PR to add SpaceVim to NixOS :-)

Cheers

**Comment by fzakaria** [comment]
Oh thank you so much for your kind words.
I think I came across it in a Tailscale guide -- maybe https://tailscale.com/kb/1077/secure-server-ubuntu-18-04

> First, we’ll set a rule to accept any incoming ssh connections over Tailscale. Tailscale uses the tailscale0 interface and port 41641 for connections, so we’ll instruct ufw to allow any traffic over those

I ended up doing `tshark` over the tailscale TUN device and you can see that is the port that is sending the Wireguard traffic.

That SpaceVim package was one of the first ones I wrote; probably should try and push it over the finish line.
It's a bit challenging getting packages in, I almost rather just make a tiny GitHub repository for overlays instead.
(Similar to what I did for https://github.com/fzakaria/lolcommits-nixpkgs)

PS: my e-mail is on the side-bar of my blog if you want to continue the conversation.
